name: ci-check

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  ci-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Type Check
        run: bun run typecheck

      - name: Lint Check
        run: bun run lint

      - name: Format Check
        run: bun run format

      - name: Test
        run: bun run test

      - name: Build Check
        run: bun run build
